### ISSUE TITLE
gRPC

### ISSUE THREAD

**Issue by mehm8128** [traPtitech/Emoine_R-UI#207]
なんか色々設定する

**Comment by mehm8128** [comment]
gRPCじゃなくてconnectだった

**Comment by ras0q** [comment]
- [ ] コード生成
- [ ] バックエンドのレポジトリから持ってくる

バックエンドは[buf](https://buf.build/docs/ecosystem/cli-overview)を使って生成を管理してる
protocでprotobufからコード生成できるが、bufは複数のprotocコマンドをまとめてくれる(あんま相性良くなかったら生protocでもいいと思う、neoshowcaseは多分生)
個人的にはbuf.gen.yamlの中で上2つのタスクを自動化した上でnpm runで実行できると一番いい

**Comment by ras0q** [comment]
bufはconnectと同じとこが作ってる

https://twitter.com/bufbuild
